// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-lEeLss5fdCYD4GzQEdAGgPBzDDuQuQ0',
    appId: '1:373606503:web:7631f1a92423fab4a3acc2',
    messagingSenderId: '373606503',
    projectId: 'landlord-file-cabinet-43702',
    authDomain: 'landlord-file-cabinet-43702.firebaseapp.com',
    storageBucket: 'landlord-file-cabinet-43702.appspot.com',
    measurementId: 'G-6M59T0Q6ZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIPDZ1BLzPStapHq--8Kefo33a_lF5H4s',
    appId: '1:373606503:android:5e5125500177a19ea3acc2',
    messagingSenderId: '373606503',
    projectId: 'landlord-file-cabinet-43702',
    storageBucket: 'landlord-file-cabinet-43702.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADTqhR5u8r3DsIACK-RQOfWzPlmhumIYw',
    appId: '1:373606503:ios:58e3949b66d01d4ea3acc2',
    messagingSenderId: '373606503',
    projectId: 'landlord-file-cabinet-43702',
    storageBucket: 'landlord-file-cabinet-43702.appspot.com',
    iosBundleId: 'com.example.landlordFileCabinet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADTqhR5u8r3DsIACK-RQOfWzPlmhumIYw',
    appId: '1:373606503:ios:1e53d4f4176be2b9a3acc2',
    messagingSenderId: '373606503',
    projectId: 'landlord-file-cabinet-43702',
    storageBucket: 'landlord-file-cabinet-43702.appspot.com',
    iosBundleId: 'com.example.landlordFileCabinet.RunnerTests',
  );
}
